# TODO : 아직 작업되지 않음 외부파라미터 세팅 필욧
lidar_camera_tf:
  ros__parameters:
    parent_frame: "velodyne"
    child_frame: "camera_right_frame"
    translation: [-0.90, -0.271260, 0.723125]
    rotation:    [-0.390402, 0.753295, -0.472325, 0.238833]   # qx, qy, qz, qws