lidar_camera_tf:
  ros__parameters:
    parent_frame: "velodyne"
    child_frame: "camera_front_down_frame"
    # translation [x, y, z]  (단위: m)
    translation: [-0.40, 0.010905, 0.450183]
    # rotation   [qx, qy, qz, qw]  (단위: unit-less, ROS 쿼터니언)
    rotation: [-0.570941, 0.569794, -0.428440, 0.407185]